### ISSUE TITLE
Integration in `scipy.stats.qmc`

### ISSUE THREAD

**Issue by tupui** [stefanv/lloyd#2]
Hey @stefanv, just saw you did this. It looks great! What do you think about integrating this to SciPy's QMC module?

There is an open PR for poisson disk sampling (a bit stalled, but I still have hopes) and I think this might be interesting too. Not sure how it generalize well in n-dimensions though.

**Comment by stefanv** [comment]
If someone found this useful, that'd be great!

The N-dimensional extension should be doable, given that QHull supports it.

One thing that will need to be addressed more carefully is that I add points outside the image (in this 2D case) to make the tesselation perform correctly.  I don't know if this is the optimal or the correct approach.  Hopefully someone on the SciPy team more familiar with QHull could help out there.

**Comment by tupui** [comment]
Glad to read! Do you want us to work together, yourself or shall I try a PR myself?

I've never dived into QHull and cool be the opportunity to do it. My interest so far was just on the sampling side and got distracted with things around Voronoï 😅 To me it looks more elegant than poisson disk sampling. For the story, I am also trying to find a way to use aperiodic tiling in n-dimensions to create a sample.

**Comment by stefanv** [comment]
Yes, please go ahead and get a PR started, then I'll work with you there to get it done.

**Comment by stefanv** [comment]
There's been some efforts to analyze convergence, BTW, but as they mentioned [on Wikipedia](https://en.wikipedia.org/wiki/Lloyd%27s_algorithm#Convergence) the results are weaker in higher dimensions.

**Comment by tupui** [comment]
FYI, I started to work on this here https://gist.github.com/tupui/3800794516775aaa3d0a45da60ede337
First step was to drop usage of Shapely (I used a simple mean for now as I am not sure if QHull could provide it, I could not find how to do this) and I made it n-D. I played a bit an added some exponential relaxation (purely based on nothing and could be wrong 😅).

**Comment by stefanv** [comment]
Excellent, I'll play with that a bit tonight!  I.t.o. licensing, I'm happy to change to whatever makes for easiest integration with SciPy (BSD, presumably).

**Comment by tupui** [comment]
Hopefully I did not do too stupid things 😉 For the license I think it's good as we explicitly list MIT as ok for integration in SciPy, but if you prefer I am also completely fine with changing it to any BSD.

**Comment by czgdp1807** [comment]
Hi. @tupui @stefanv Can I work on integrating this to SciPy? I saw that there is no PR linked to https://github.com/scipy/scipy/issues/14510 where this issue is listed as one of the tasks. Let me know. Thanks.

**Comment by tupui** [comment]
> Hi. @tupui @stefanv Can I work on integrating this to SciPy? I saw that there is no PR linked to [scipy/scipy#14510](https://github.com/scipy/scipy/issues/14510) where this issue is listed as one of the tasks. Let me know. Thanks.

Hi @czgdp1807 thanks for your interest! I actually did a gist (see above) which I plan to submit as a PR. But if the subject interests you, this will need other eyes and reviews and I would gladly read your thoughts/work together with you. In the meantime, feel free to comment the gist.

If you are looking to do something else along the line, the current PR on poisson disk sampling is quite stalled. This one could really use some help and IMO would have more impact as it's a widely used technique. Feel free to come by and propose some help if you'd like.

**Comment by stefanv** [comment]
@tupui I had a quick look at the gist yesterday. Note that there are some indentation issues and that it misses a plt.show for using from a terminal.

The relaxation looks reasonable, FWIW! Not sure if 2 is where to start, but 🤷‍♂️

I will play with it more soon.

**Comment by tupui** [comment]
> @tupui I had a quick look at the gist yesterday. Note that there are some indentation issues and that it misses a plt.show for using from a terminal.

Thanks for having a look! I will fixes these issues thanks 🙏 

> The relaxation looks reasonable, FWIW! Not sure if 2 is where to start, but 🤷‍♂️

Yeah here I did not read yet the literature. I am not sure/convinced that this is optimal.

> I will play with it more soon. 

Shall I wait to make a PR?

**Comment by stefanv** [comment]
It looks like this version only operates on rectangles, not arbitrary regions. Is that sufficient? 

Also, how did you choose the extension points outside the data? From the code it looks like 0 and 1, but I'm obviously missing something.

**Comment by tupui** [comment]
> It looks like this version only operates on rectangles, not arbitrary regions. Is that sufficient?

It does. Right now in SciPy we only support rectangles (hypercubes). IMO we should restrict this at first to hypercube and maybe think more in general how to handle non rectangular domains.

> Also, how did you choose the extension points outside the data? From the code it looks like 0 and 1, but I'm obviously missing something.

Here it probably needs more work. Right now I am just adding all corner points and clip everything outside of the domain. But as you probably see, it avoids too much the bounds and tend to produce something more like a hypersphere.

**Comment by tupui** [comment]
I played a bit more with the corners and I think we can get away with something simple like this

```python
d = centroids.shape[1]
arrays = np.tile([0 - rng.random()/10, 1 + rng.random()/10], (d, 1))
hypercube_corners = np.stack(np.meshgrid(*arrays), axis=-1).reshape(-1, d)
```
So adding some noise to prevent the points to get aligned on the boundary at a fixed distance. What do you think?

I am not sure about the interface for SciPy here. It looks like this could either be a `QMCEngine` or just a function. This could then be used to "relax" any sample (if given). I can see myself running a few iteration of this over Sobol' for instance.

**Comment by stefanv** [comment]
Why would adding a random number save us from being aligned with the boundary.  Is there a reason to not simply put those corners diagonally outside the corners by a factor of the maximum data value?

**Comment by tupui** [comment]
> Why would adding a random number save us from being aligned with the boundary. Is there a reason to not simply put those corners diagonally outside the corners by a factor of the maximum data value?

I do want to pad the boundary but with a variable factor. My rational is: as the iterations goes we can see that all cells from the center out have a similar shape and size and it forces the boundary points to the corners. If we have a fixed factor, then the points are just "sliding" on the boundaries. Then adding some randomness on the padding could mitigate a bit this sliding.

Otherwize I thought about giving a fixed value, but what value? My first guess would to have at most a point on the boundary. Then the centroid of a cell on a corner point leading to a padding of `pad = 1/( (n**(1/d)) - 1 )` (assuming a grid of points). But then we risk to have all points close to a boundary to fall on the boundary. Hence again the idea of randomization (which should be at most `pad`).

**Comment by stefanv** [comment]
It may be worth coming up with some fitness metrics so we can evaluate the different approaches.  E.g., we could say: each centroid's cell should span roughly the same area, and the collection of inter-centroid distances should have low variance.

**Comment by tupui** [comment]
> It may be worth coming up with some fitness metrics so we can evaluate the different approaches. E.g., we could say: each centroid's cell should span roughly the same area, and the collection of inter-centroid distances should have low variance.

I have some code for the discrepancy, minimal spanning tree and some other distance based metrics I can try on. I would stay with such global metrics as in the end they are the ones that matter in practice.

**Comment by tupui** [comment]
From first tests it's not really clear that it does much actually.

```
# Metrics: L1, L2, Linf, C2, WD, MD
# first 3 higher is better, then lower is better

# n = 128, d = 2, n_conv = 20, n_iters = 10
Case 0: [0.03756396 0.03235515 0.02977426 0.00276655 0.00273227 0.00357682]
Case 1: [0.02963416 0.02440085 0.02222918 0.00265475 0.00282469 0.00356549]
Case 2: [0.0420796  0.03731389 0.03528    0.0022464  0.00235018 0.00299628]

# n = 128, d = 5, n_conv = 10, n_iters = 10
Case 0: [0.26573296 0.1499547  0.11208187 0.01171247 0.0253029  0.04989028]
Case 1: [0.22467091 0.1341176  0.1009514  0.01036004 0.0216108  0.04280959]
Case 2: [0.26147786 0.14193581 0.09652452 0.01067324 0.02611038 0.04811094]
```

with
```python
    if case == 0:
        arrays = np.tile([0, 1], (d, 1))
    elif case == 1:
        arrays = np.tile([0-2, 1+2], (d, 1))
    elif case == 2:
        pad = 1/(len(points)**(1/d) - 1)
        arrays = np.tile([0-rng.random()*pad, 1+rng.random()*pad], (d, 1))

    hypercube_corners = np.stack(np.meshgrid(*arrays), axis=-1).reshape(-1, d)
```

But maybe I am missing something or have a bug.

**Comment by stefanv** [comment]
Case 2 does seem to perform better; maybe also try it with a value larger than 2.

**Comment by tupui** [comment]
Here it is with 100. In higher dimensions the effect is still less visible.
```
# Metrics: L1, L2, Linf, C2, WD, MD
# first 3 higher is better, then lower is better

# n = 128, d = 2, n_conv = 20, n_iters = 10
Case 0: [0.03756396 0.03235515 0.02977426 0.00276655 0.00273227 0.00357682]
Case 1: [0.03032333 0.02606944 0.02442665 0.00264631 0.00281324 0.00356969]
Case 2: [0.0420796  0.03731389 0.03528    0.0022464  0.00235018 0.00299628]

# n = 128, d = 5, n_conv = 10, n_iters = 10
Case 0: [0.26573296 0.1499547  0.11208187 0.01171247 0.0253029  0.04989028]
Case 1: [0.21670567 0.13509082 0.1009514  0.0103644  0.021182   0.04221403]
Case 2: [0.26147786 0.14193581 0.09652452 0.01067324 0.02611038 0.04811094]
```

FTR, here is the notebook I am playing in.
[qmc_experiments.ipynb.zip](https://github.com/stefanv/lloyd/files/6974506/qmc_experiments.ipynb.zip)

**Comment by stefanv** [comment]
Sorry, I mean to say case 1 above.  I am looking at L2.  Still seems significant in both cases, but the larger number does not improve things it seems.

**Comment by stefanv** [comment]
In higher dimensions, spaces behave oddly.  My intuition is that hypercubes have "sharp" corners and tend more towards spheres (I could be mistaken), but that would explain some of it.

**Comment by tupui** [comment]
> Sorry, I mean to say case 1 above. I am looking at L2. Still seems significant in both cases, but the larger number does not improve things it seems.

I did change case 1 and not 2.

> In higher dimensions, spaces behave oddly. My intuition is that hypercubes have "sharp" corners and tend more towards spheres (I could be mistaken), but that would explain some of it.

Right and I guess also just changing corners does not do much then as the space becomes enormous and corners less and less important. If we could instead add the whole surface if would be different I guess.

Do you think I have enough now to start a PR? Or we should experiment more things before?

**Comment by stefanv** [comment]
I think this is a solid start; go for it.

**Comment by tupui** [comment]
I can add you as co-author of the commits I would make if you'd like?

**Comment by stefanv** [comment]
Sure, that'd be nice of you; not necessary, but nice :)

**Comment by tupui** [comment]
Actually when plotting, your solution seems better (2) as it mitigates better the going to a hypersphere.

Case 0
<img width="273" alt="0" src="https://user-images.githubusercontent.com/23188539/130358414-7f2f5a78-80e5-46c4-b1e7-bea80b984706.png">
Case 1
<img width="272" alt="1" src="https://user-images.githubusercontent.com/23188539/130358415-fd7abe29-0e0a-47bd-a554-5e4582f397a1.png">
Case 2
<img width="287" alt="2" src="https://user-images.githubusercontent.com/23188539/130358413-66feda61-5efc-440a-8313-e398268e3cb7.png">

**Comment by tupui** [comment]
I created a [branch](https://github.com/tupui/scipy/tree/lloyd ) in my fork and gave you access. Feel free to commit on it 😃 I will soon make this a real PR. Still need to add a test and a bit more doc (especially to warn about high dimensionality costs). I am not sure if there is other things to test otherwise. Let me know what you think.

I am not sure if this should maybe go in a dedicated file instead. (Well in the end, I would have preferred QMC to be it's own module. IMHO makes more sense). Here I could make a QMC folder in `stats` as we start to have a few files for QMC.

**Comment by tupui** [comment]
Closing as now in SciPy 1.9
